# Generated by Django 3.0.8 on 2021-09-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='method',
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('cd', 'Card'), ('ch', 'Cash')], default='cd', max_length=9),
        ),
    ]
