# Generated by Django 3.0.8 on 2021-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210928_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.AddField(
            model_name='expense',
            name='method_payment',
            field=models.CharField(choices=[('CD', 'Card'), ('CH', 'Cash')], default='CD', max_length=9),
        ),
    ]
